/*
 * Eurosign
 * This is the documentation of the eurosign API, you can download all of our SDK in this page.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eurosign.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import Eurosign.ApiException;
import io.swagger.client.model.Body;
import io.swagger.client.model.Body1;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SignatureRequestsApi
 */
@Ignore
public class SignatureRequestsApiTest {

    private final SignatureRequestsApi api = new SignatureRequestsApi();

    /**
     * Cancel a signature requests
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelSignatureRequestsTest() throws ApiException {
        String uuid = null;
        api.cancelSignatureRequests(uuid);

        // TODO: test validations
    }
    /**
     * Create a new signature request
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSignatureRequestTest() throws ApiException {
        Body body = null;
        InlineResponse2001 response = api.createSignatureRequest(body);

        // TODO: test validations
    }
    /**
     * Get signature requests test
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSignatureRequestTest() throws ApiException {
        String uuid = null;
        api.getSignatureRequest(uuid);

        // TODO: test validations
    }
    /**
     * Get the audit report of a signature requests
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSignatureRequestAuditTrailTest() throws ApiException {
        String uuid = null;
        api.getSignatureRequestAuditTrail(uuid);

        // TODO: test validations
    }
    /**
     * Get a recipient of a signature requests
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSignatureRequestRecipientTest() throws ApiException {
        String uuid = null;
        String recipientUuid = null;
        api.getSignatureRequestRecipient(uuid, recipientUuid);

        // TODO: test validations
    }
    /**
     * Get recipients of a signature requests
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSignatureRequestRecipientsTest() throws ApiException {
        String uuid = null;
        api.getSignatureRequestRecipients(uuid);

        // TODO: test validations
    }
    /**
     * Get the list of signature requests
     *
     * Retrieve the list of all the signature requests
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSignatureRequestsTest() throws ApiException {
        InlineResponse200 response = api.getSignatureRequests();

        // TODO: test validations
    }
    /**
     * Send a signature requests
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendSignatureRequestTest() throws ApiException {
        String uuid = null;
        String senderId = null;
        api.sendSignatureRequest(uuid, senderId);

        // TODO: test validations
    }
    /**
     * Update a signature requests
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSignatureRequestTest() throws ApiException {
        String uuid = null;
        Body1 body = null;
        api.updateSignatureRequest(uuid, body);

        // TODO: test validations
    }
}
